import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@lib/utils";
import { Navbar } from "@components/layout";
import { BackgroundGradient } from "@components/shared";
import "@styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { JotaiProvider } from "@providers/jotai-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(inter.className)}>
          <JotaiProvider>
            <BackgroundGradient />
            <Navbar />
            <section className="h-screen w-full flex flex-col items-center justify-center">
              {children}
            </section>
          </JotaiProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
